# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: city.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='city.proto',
  package='br.com.gprcexample.grpc.services',
  syntax='proto3',
  serialized_options=b'\n br.com.gprcexample.grpc.servicesB\020CityServiceProtoP\001',
  serialized_pb=b'\n\ncity.proto\x12 br.com.gprcexample.grpc.services\"\x18\n\nCitRequest\x12\n\n\x02id\x18\x01 \x01(\t\"N\n\tCityReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x03 \x01(\t\x12\x12\n\npopulation\x18\x04 \x01(\t2y\n\x0b\x43ityService\x12j\n\x0bgetCityById\x12,.br.com.gprcexample.grpc.services.CitRequest\x1a+.br.com.gprcexample.grpc.services.CityReply\"\x00\x42\x36\n br.com.gprcexample.grpc.servicesB\x10\x43ityServiceProtoP\x01\x62\x06proto3'
)




_CITREQUEST = _descriptor.Descriptor(
  name='CitRequest',
  full_name='br.com.gprcexample.grpc.services.CitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='br.com.gprcexample.grpc.services.CitRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=72,
)


_CITYREPLY = _descriptor.Descriptor(
  name='CityReply',
  full_name='br.com.gprcexample.grpc.services.CityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='br.com.gprcexample.grpc.services.CityReply.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='br.com.gprcexample.grpc.services.CityReply.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='countryCode', full_name='br.com.gprcexample.grpc.services.CityReply.countryCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='population', full_name='br.com.gprcexample.grpc.services.CityReply.population', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['CitRequest'] = _CITREQUEST
DESCRIPTOR.message_types_by_name['CityReply'] = _CITYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CitRequest = _reflection.GeneratedProtocolMessageType('CitRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:br.com.gprcexample.grpc.services.CitRequest)
  })
_sym_db.RegisterMessage(CitRequest)

CityReply = _reflection.GeneratedProtocolMessageType('CityReply', (_message.Message,), {
  'DESCRIPTOR' : _CITYREPLY,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:br.com.gprcexample.grpc.services.CityReply)
  })
_sym_db.RegisterMessage(CityReply)


DESCRIPTOR._options = None

_CITYSERVICE = _descriptor.ServiceDescriptor(
  name='CityService',
  full_name='br.com.gprcexample.grpc.services.CityService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=275,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCityById',
    full_name='br.com.gprcexample.grpc.services.CityService.getCityById',
    index=0,
    containing_service=None,
    input_type=_CITREQUEST,
    output_type=_CITYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CITYSERVICE)

DESCRIPTOR.services_by_name['CityService'] = _CITYSERVICE

# @@protoc_insertion_point(module_scope)
