# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.stubs.city_pb2 as city__pb2


class CityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCityById = channel.unary_unary(
        '/br.com.gprcexample.grpc.services.CityService/getCityById',
        request_serializer=city__pb2.CitRequest.SerializeToString,
        response_deserializer=city__pb2.CityReply.FromString,
        )


class CityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCityById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCityById': grpc.unary_unary_rpc_method_handler(
          servicer.getCityById,
          request_deserializer=city__pb2.CitRequest.FromString,
          response_serializer=city__pb2.CityReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'br.com.gprcexample.grpc.services.CityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
